# Generated by Django 2.2 on 2021-05-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='costPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='nShares',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='totalGain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='totalGainInDollars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
